# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
  - stage: Build
    jobs:
    - job: run_build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          npm install -g @angular/cli
          npm install
          ng build --prod
        displayName: 'npm install and build'


          
# - task: DeleteFiles@1
#   displayName: 'Delete JUnit files'
#   inputs:
#     SourceFolder: ./junit
#     Contents: 'TESTS*.xml'
    
# - task: PublishTestResults@2
#   displayName: 'Publish Angular test results'
#   condition: succeededOrFailed()
#   inputs:
#     searchFolder: ./junit
#     testRunTitle: Angular
#     testResultsFormat: JUnit
#     testResultsFiles: "**/TESTS*.xml"


